/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my_billing_system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author Mehmoob Ahmad
 */
public class Login extends javax.swing.JFrame {

    DefaultTableModel tpr;
    DefaultTableModel td;
    DefaultTableModel tb;
    DefaultTableModel ts;
    
    DefaultComboBoxModel cm;
    
    
    //...DATABASE REQ ...........
    
    Connection con;
    ResultSet set;
    PreparedStatement pstmt;
    Statement st ;
    
    
    public Login() {
        initComponents();
        setResizable(false);
        
        //... combo box ....
        cm = new DefaultComboBoxModel();
        compr.setModel(cm);
        
        
        //.... table view screen ........
        tpr = new DefaultTableModel();
        tp.setModel(tpr);
        
        //.... setting columns .........
         tpr.addColumn("ID");
         tpr.addColumn("Name of Item");
         tpr.addColumn("Price");
         tpr.addColumn("Quantity");
         
         
         //.... table delete screen ........
        td = new DefaultTableModel();
        tdel.setModel(td);
        
        //.... setting columns .........
         td.addColumn("ID");
         td.addColumn("Name of Item");
         td.addColumn("Price");
         td.addColumn("Quantity");
         
         
         //.... table view screen ........
        tb = new DefaultTableModel();
        tbil.setModel(tb);
        
        //.... setting columns .........
         
         tb.addColumn("Name of Item");
         tb.addColumn("Price");
         tb.addColumn("Quantity");
         
          //.... table view screen ........
        ts = new DefaultTableModel();
        tsr.setModel(ts);
        
        //.... setting columns .........
         ts.addColumn("Sno");
         ts.addColumn("Name of Customer");
         ts.addColumn("Total Bill");
         ts.addColumn("Date");
         
         //...date..........
         date();
         
         
         AutoCompleteDecorator.decorate(compr);
         
         String currentdir = System.getProperty("user.dir");
         //...coneCting TO Database .............
          try {
              
              Class.forName("org.apache.derby.jdbc.ClientDriver");
              
              con = DriverManager.getConnection("jdbc:derby:"+currentdir+"/My" , "MA" , "23664");
          
              JOptionPane.showMessageDialog(rootPane, "Connected");
              
          }catch (Exception ex) {
              ex.printStackTrace();
              JOptionPane.showMessageDialog(rootPane, "Not Connected");
          }
          
          
    }
    
    public String date()
    {
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("dd/MM/yyyy");
        
        date.setText(s.format(d));
        return s.format(d);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Main = new javax.swing.JPanel();
        mm = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        prmm = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        addp = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        pqt = new javax.swing.JTextField();
        ppr = new javax.swing.JTextField();
        pnm = new javax.swing.JTextField();
        jButton19 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton20 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        viewp = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tp = new javax.swing.JTable();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        updatep = new javax.swing.JPanel();
        deletep = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tdel = new javax.swing.JTable();
        txdel = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        billingScreen = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jButton36 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbil = new javax.swing.JTable();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        cusnm = new javax.swing.JTextField();
        compr = new javax.swing.JComboBox();
        bal = new javax.swing.JTextField();
        pr = new javax.swing.JTextField();
        jButton40 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        quan = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        total = new javax.swing.JTextField();
        paid = new javax.swing.JTextField();
        date = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        quan1 = new javax.swing.JLabel();
        salerec = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tsr = new javax.swing.JTable();
        jButton42 = new javax.swing.JButton();
        jButton43 = new javax.swing.JButton();
        jButton44 = new javax.swing.JButton();
        jButton45 = new javax.swing.JButton();
        jButton46 = new javax.swing.JButton();
        jButton47 = new javax.swing.JButton();
        txd = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1500, 820));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        Main.setBackground(new java.awt.Color(0, 51, 51));
        Main.setPreferredSize(new java.awt.Dimension(1481, 830));
        Main.setLayout(new javax.swing.BoxLayout(Main, javax.swing.BoxLayout.LINE_AXIS));

        mm.setBackground(new java.awt.Color(255, 255, 255));
        mm.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 70)); // NOI18N
        jLabel1.setText("POS BILLING SYSTEM");
        mm.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, 790, -1));

        jButton1.setBackground(new java.awt.Color(0, 102, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Products Menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        mm.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 460, 360, 90));

        jButton4.setBackground(new java.awt.Color(255, 0, 51));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("EXIT");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        mm.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1380, 10, -1, -1));

        jButton5.setBackground(new java.awt.Color(0, 102, 0));
        jButton5.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Billing Screen");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        mm.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 330, 520, 80));

        jButton6.setBackground(new java.awt.Color(0, 102, 0));
        jButton6.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("View Sales");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        mm.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 460, 360, 90));

        jButton11.setBackground(new java.awt.Color(51, 102, 0));
        mm.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 720, 1490, 30));

        jButton12.setBackground(new java.awt.Color(51, 102, 0));
        mm.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 1490, 20));

        jButton13.setBackground(new java.awt.Color(51, 102, 0));
        mm.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1490, 20));

        jButton14.setBackground(new java.awt.Color(51, 102, 0));
        mm.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 670, 1490, 30));

        Main.add(mm);

        prmm.setBackground(new java.awt.Color(255, 255, 255));
        prmm.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(51, 102, 0));
        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 70)); // NOI18N
        jLabel2.setText("Products Menu");
        prmm.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, 550, 160));

        jButton2.setBackground(new java.awt.Color(51, 102, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Update Products");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        prmm.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 490, 440, 100));

        jButton3.setBackground(new java.awt.Color(51, 102, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Add Products");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        prmm.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 330, 440, 100));

        jButton7.setBackground(new java.awt.Color(51, 102, 0));
        jButton7.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("View Products");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        prmm.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 440, 100));

        jButton8.setBackground(new java.awt.Color(51, 102, 0));
        jButton8.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Delete Products");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        prmm.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 490, 440, 100));

        jButton9.setBackground(new java.awt.Color(255, 0, 51));
        jButton9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("EXIT");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        prmm.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 20, 130, 50));

        jButton10.setBackground(new java.awt.Color(51, 204, 0));
        jButton10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("BACK");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        prmm.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 130, 50));

        jButton15.setBackground(new java.awt.Color(51, 102, 0));
        prmm.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 750, 1490, 30));

        jButton16.setBackground(new java.awt.Color(51, 102, 0));
        prmm.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 670, 1490, 30));

        jButton17.setBackground(new java.awt.Color(51, 102, 0));
        prmm.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 1490, 20));

        jButton18.setBackground(new java.awt.Color(51, 102, 0));
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        prmm.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1490, 20));

        Main.add(prmm);

        addp.setBackground(new java.awt.Color(255, 255, 255));
        addp.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 70)); // NOI18N
        jLabel3.setText("Add Products");
        addp.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, 490, 110));

        pqt.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        addp.add(pqt, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 510, 440, 60));

        ppr.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        addp.add(ppr, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 380, 440, 60));

        pnm.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        pnm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pnmActionPerformed(evt);
            }
        });
        addp.add(pnm, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 260, 440, 60));

        jButton19.setBackground(new java.awt.Color(255, 102, 51));
        jButton19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton19.setForeground(new java.awt.Color(255, 255, 255));
        jButton19.setText("SAVE");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        addp.add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 640, 180, 60));

        jLabel4.setBackground(new java.awt.Color(51, 102, 0));
        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 102, 0));
        jLabel4.setText("Enter Quantity");
        addp.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 510, 230, 60));

        jLabel5.setBackground(new java.awt.Color(51, 102, 0));
        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 102, 0));
        jLabel5.setText("Enter Name");
        addp.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 220, 60));

        jLabel6.setBackground(new java.awt.Color(51, 102, 0));
        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 102, 0));
        jLabel6.setText("Enter Price");
        addp.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, 200, 60));

        jButton20.setBackground(new java.awt.Color(51, 204, 0));
        jButton20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton20.setText("BACK");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        addp.add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 110, 40));

        jButton27.setBackground(new java.awt.Color(51, 102, 0));
        jButton27.setForeground(new java.awt.Color(51, 102, 0));
        addp.add(jButton27, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 1490, 20));

        jButton28.setBackground(new java.awt.Color(51, 102, 0));
        jButton28.setForeground(new java.awt.Color(51, 102, 0));
        jButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton28ActionPerformed(evt);
            }
        });
        addp.add(jButton28, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1490, 20));

        Main.add(addp);

        viewp.setBackground(new java.awt.Color(255, 255, 255));
        viewp.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 70)); // NOI18N
        jLabel7.setText("View Products");
        viewp.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, 530, 120));

        tp.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        tp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tp);

        viewp.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 1490, 350));

        jButton21.setBackground(new java.awt.Color(51, 204, 0));
        jButton21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton21.setForeground(new java.awt.Color(255, 255, 255));
        jButton21.setText("BACK");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        viewp.add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 40));

        jButton22.setBackground(new java.awt.Color(255, 0, 0));
        jButton22.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton22.setForeground(new java.awt.Color(255, 255, 255));
        jButton22.setText("EXIT");
        viewp.add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 10, -1, 40));

        jButton23.setBackground(new java.awt.Color(0, 0, 0));
        viewp.add(jButton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 610, 1490, 10));

        jButton29.setBackground(new java.awt.Color(51, 102, 0));
        viewp.add(jButton29, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 1490, 20));

        jButton30.setBackground(new java.awt.Color(51, 102, 0));
        jButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton30ActionPerformed(evt);
            }
        });
        viewp.add(jButton30, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1490, 20));

        jButton31.setBackground(new java.awt.Color(0, 0, 0));
        viewp.add(jButton31, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 1490, 10));

        Main.add(viewp);
        Main.add(updatep);

        deletep.setBackground(new java.awt.Color(255, 255, 255));
        deletep.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 70)); // NOI18N
        jLabel8.setText("Delete Products");
        deletep.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 590, 100));

        tdel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        tdel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tdel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tdelMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tdel);

        deletep.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 1490, 330));

        txdel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        deletep.add(txdel, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 620, 310, 50));

        jLabel9.setBackground(new java.awt.Color(51, 102, 0));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 102, 0));
        jLabel9.setText("ID of Item to Delete");
        deletep.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 620, -1, 50));

        jButton25.setBackground(new java.awt.Color(255, 102, 0));
        jButton25.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton25.setForeground(new java.awt.Color(255, 255, 255));
        jButton25.setText("DELETE");
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });
        deletep.add(jButton25, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 690, 200, 50));

        jButton26.setBackground(new java.awt.Color(51, 204, 0));
        jButton26.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton26.setForeground(new java.awt.Color(255, 255, 255));
        jButton26.setText("BACK");
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });
        deletep.add(jButton26, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 40));

        jButton32.setBackground(new java.awt.Color(51, 102, 0));
        jButton32.setForeground(new java.awt.Color(51, 102, 0));
        jButton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton32ActionPerformed(evt);
            }
        });
        deletep.add(jButton32, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1490, 20));

        jButton33.setBackground(new java.awt.Color(51, 102, 0));
        jButton33.setForeground(new java.awt.Color(51, 102, 0));
        deletep.add(jButton33, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 1490, 20));

        jButton34.setBackground(new java.awt.Color(0, 0, 0));
        deletep.add(jButton34, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 1490, 10));

        jButton35.setBackground(new java.awt.Color(0, 0, 0));
        deletep.add(jButton35, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, 1490, 10));

        Main.add(deletep);

        billingScreen.setBackground(new java.awt.Color(255, 255, 255));
        billingScreen.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Tahoma", 3, 70)); // NOI18N
        jLabel10.setText("Billing Screen");
        billingScreen.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 50, 510, 120));

        jButton36.setBackground(new java.awt.Color(0, 0, 0));
        billingScreen.add(jButton36, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 700, 1490, -1));

        tbil.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        tbil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbilMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbil);

        billingScreen.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 1050, 240));

        jButton37.setBackground(new java.awt.Color(0, 0, 0));
        billingScreen.add(jButton37, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 1490, -1));

        jButton38.setBackground(new java.awt.Color(51, 102, 0));
        jButton38.setForeground(new java.awt.Color(51, 102, 0));
        billingScreen.add(jButton38, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 1490, 20));

        jButton39.setBackground(new java.awt.Color(51, 102, 0));
        jButton39.setForeground(new java.awt.Color(51, 102, 0));
        jButton39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton39ActionPerformed(evt);
            }
        });
        billingScreen.add(jButton39, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1490, 20));

        jButton24.setText("Back");
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });
        billingScreen.add(jButton24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 102, 0));
        jLabel11.setText("Enter Name Of Customer");
        billingScreen.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 390, 40));

        cusnm.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        billingScreen.add(cusnm, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 420, 40));

        compr.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        compr.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        compr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprActionPerformed(evt);
            }
        });
        billingScreen.add(compr, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 350, 40));

        bal.setBackground(new java.awt.Color(102, 102, 102));
        bal.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        bal.setForeground(new java.awt.Color(255, 255, 255));
        bal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balActionPerformed(evt);
            }
        });
        billingScreen.add(bal, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 620, 230, 60));

        pr.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        billingScreen.add(pr, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 370, 230, 40));

        jButton40.setBackground(new java.awt.Color(255, 102, 0));
        jButton40.setFont(new java.awt.Font("Tahoma", 1, 32)); // NOI18N
        jButton40.setForeground(new java.awt.Color(255, 255, 255));
        jButton40.setText("+");
        jButton40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton40ActionPerformed(evt);
            }
        });
        billingScreen.add(jButton40, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 360, 60, 50));

        jButton41.setBackground(new java.awt.Color(0, 102, 0));
        jButton41.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton41.setForeground(new java.awt.Color(255, 255, 255));
        jButton41.setText("SAVE");
        jButton41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton41ActionPerformed(evt);
            }
        });
        billingScreen.add(jButton41, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 720, 140, 40));

        jLabel12.setBackground(new java.awt.Color(0, 153, 102));
        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 102, 0));
        jLabel12.setText(" TOTAL : ");
        billingScreen.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 470, 170, 60));

        quan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        billingScreen.add(quan, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 370, 230, 40));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 102, 0));
        jLabel13.setText(" Balance :");
        billingScreen.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 620, 190, 60));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 102, 0));
        jLabel14.setText(" Paid :");
        billingScreen.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 550, 140, 60));

        total.setBackground(new java.awt.Color(51, 102, 0));
        total.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        total.setForeground(new java.awt.Color(255, 255, 255));
        total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalActionPerformed(evt);
            }
        });
        billingScreen.add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 470, 260, 70));

        paid.setBackground(new java.awt.Color(0, 51, 0));
        paid.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        paid.setForeground(new java.awt.Color(255, 255, 255));
        paid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paidActionPerformed(evt);
            }
        });
        billingScreen.add(paid, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 540, 260, 80));

        date.setBackground(new java.awt.Color(51, 102, 0));
        date.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        date.setForeground(new java.awt.Color(51, 102, 0));
        billingScreen.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 240, 220, 30));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 102, 0));
        jLabel16.setText("Select Item");
        billingScreen.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 190, 30));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 102, 0));
        jLabel17.setText("Date");
        billingScreen.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 200, 80, 30));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 102, 0));
        jLabel18.setText("Price");
        billingScreen.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 330, 80, 30));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 102, 0));
        jLabel19.setText("Quantity");
        billingScreen.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 330, 140, 30));

        quan1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        billingScreen.add(quan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 416, 290, 20));

        Main.add(billingScreen);

        salerec.setBackground(new java.awt.Color(255, 255, 255));
        salerec.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Tahoma", 3, 70)); // NOI18N
        jLabel15.setText("View Sales Report");
        salerec.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, 680, 120));

        tsr.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        tsr.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tsr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tsrMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tsr);

        salerec.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 1490, 330));

        jButton42.setBackground(new java.awt.Color(51, 204, 0));
        jButton42.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton42.setForeground(new java.awt.Color(255, 255, 255));
        jButton42.setText("BACK");
        jButton42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton42ActionPerformed(evt);
            }
        });
        salerec.add(jButton42, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 40));

        jButton43.setBackground(new java.awt.Color(0, 0, 0));
        salerec.add(jButton43, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 590, 1490, 10));

        jButton44.setBackground(new java.awt.Color(0, 102, 0));
        salerec.add(jButton44, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 1490, 20));

        jButton45.setBackground(new java.awt.Color(0, 102, 0));
        jButton45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton45ActionPerformed(evt);
            }
        });
        salerec.add(jButton45, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1490, 20));

        jButton46.setBackground(new java.awt.Color(0, 0, 0));
        salerec.add(jButton46, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 1490, 10));

        jButton47.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton47.setText("DELETE");
        jButton47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton47ActionPerformed(evt);
            }
        });
        salerec.add(jButton47, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 650, 150, 60));
        salerec.add(txd, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 610, 210, 50));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel20.setText("ID Of Bill To Delete");
        salerec.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 620, 240, 40));

        Main.add(salerec);

        getContentPane().add(Main);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
       Main.removeAll();
       Main.add(viewp);
       Main.revalidate();
       Main.repaint();
       
          try {
              
              String q2 = "select count(id) from item";
              
              pstmt = con.prepareStatement(q2);
             
              set = pstmt.executeQuery();
              
              while(set.next())
              {
                int rowcount = Integer.parseInt(set.getString(1));
                
                tpr.setRowCount(rowcount);
              }
              
              
              String q = "select * from item";
              st = con.createStatement();
              set = st.executeQuery(q);
              
              int ii = 0;
              while(set.next())
              {
                tpr.setValueAt(set.getInt(1), ii, 0);
                tpr.setValueAt(set.getString(2), ii, 1);
                tpr.setValueAt(set.getDouble(3), ii, 2);
                tpr.setValueAt(set.getInt(4), ii, 3);

                ii++;
              }
              
       
              
          }catch (Exception ex) {
              ex.printStackTrace();
          }
          
          
     
      
       
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        Main.removeAll();
        Main.add(deletep);
        Main.revalidate();
        Main.repaint();
       
       
          try {
              
              
          
              String q2 = "select count(id) from item";
              
              pstmt = con.prepareStatement(q2);
             
              set = pstmt.executeQuery();
              
              while(set.next())
              {
                int rowcount = Integer.parseInt(set.getString(1));
                
                td.setRowCount(rowcount);
              }
              
              String q = "select * from item";
             st = con.createStatement();
              set = st.executeQuery(q);
              
              int ii = 0;
              while(set.next())
              {
                
                td.setValueAt(set.getInt(1), ii, 0);
                td.setValueAt(set.getString(2), ii, 1);
                td.setValueAt(set.getDouble(3), ii, 2);
                td.setValueAt(set.getInt(4), ii, 3);

                ii++;
              }
              
       
              
          }catch (Exception ex) {
              ex.printStackTrace();
          }
          
          
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       Main.removeAll();
       Main.add(prmm);
       Main.revalidate();
       Main.repaint();
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
       Main.removeAll();
       Main.add(mm);
       Main.revalidate();
       Main.repaint();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
       System.exit(0);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       Main.removeAll();
       Main.add(addp);
       Main.revalidate();
       Main.repaint();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
       Main.removeAll();
       Main.add(prmm);
       Main.revalidate();
       Main.repaint();
    }//GEN-LAST:event_jButton20ActionPerformed

    private void pnmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pnmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pnmActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
         
        
        
        try {
            String name = pnm.getText().toString();
            double price = Double.parseDouble(ppr.getText().toString());
            int quantity = Integer.parseInt(pqt.getText().toString());
            
            
             String sql ="insert into item(nm,pr,qt) values(?,?,?)";

             pstmt=con.prepareStatement(sql);
            
            pstmt.setString(1, name);
            pstmt.setDouble(2, price);
            pstmt.setInt(3, quantity);
            
            pstmt.executeUpdate();
            
            JOptionPane.showMessageDialog(rootPane, "Sucessfully Added To MySQL");
            
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
       Main.removeAll();
       Main.add(prmm);
       Main.revalidate();
       Main.repaint();
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
       Main.removeAll();
       Main.add(prmm);
       Main.revalidate();
       Main.repaint();
    }//GEN-LAST:event_jButton26ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
       int id = Integer.parseInt(txdel.getText());
       
       try {
              
             
              if(tdel.getSelectedRowCount() >= 1)
              {
                String q = "delete from item where id=?";
             
                pstmt=con.prepareStatement(q);
            
              
                pstmt.setInt(1 , id);
            
                pstmt.executeUpdate();
              
                td.removeRow(tdel.getSelectedRow());
                
                
                JOptionPane.showMessageDialog(rootPane, "Sucessfully Deleted\nPlease Restart App To Get Updated Results...");
                
              }
              
              else if(tdel.getSelectedRowCount() == 0)
              {
                JOptionPane.showMessageDialog(rootPane, "Table is Empty");
              }
              
              else{
                JOptionPane.showMessageDialog(rootPane, "Please Select a singal row");
              }
         
              
          }catch (Exception ex) {
              ex.printStackTrace();
          }
          
       
    }//GEN-LAST:event_jButton25ActionPerformed

    private void tdelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tdelMouseClicked
       int index = tdel.getSelectedRow();
       
       int id =  (int) td.getValueAt(index , 0);
       
       txdel.setText(""+id);
       
       
    }//GEN-LAST:event_tdelMouseClicked

    private void jButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton28ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton28ActionPerformed

    private void jButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton30ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton30ActionPerformed

    private void jButton32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton32ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton32ActionPerformed

    private void tbilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbilMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbilMouseClicked

    private void jButton39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton39ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton39ActionPerformed

    private void balActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_balActionPerformed

    private void totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Main.removeAll();
        Main.add(billingScreen);
        Main.revalidate();
        Main.repaint();
        
        try{
        
           
            String sql ="select * from item";

             st = con.createStatement();

             set = st.executeQuery(sql);

            while(set.next())
            {
              String itemname = set.getString(2);
             
              cm.addElement(itemname);
            }
                    
           }catch(Exception ex){
               ex.printStackTrace();
          }

    }//GEN-LAST:event_jButton5ActionPerformed

    private void paidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paidActionPerformed
       double total_bill = Double.parseDouble(total.getText());
       double paid_bill = Double.parseDouble(paid.getText());
       
       if(total_bill >= paid_bill)
       {
          double balance = total_bill - paid_bill;
          bal.setText(" -"+balance);
          JOptionPane.showMessageDialog(rootPane, "Payment is less than Total Bill\nTake RS "+balance+" more from Customer");
       }
      
       else if( paid_bill >= total_bill)
       {
         double balance =  paid_bill - total_bill;
         bal.setText(" "+balance);
         
       }
       
    }//GEN-LAST:event_paidActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        Main.removeAll();
        Main.add(mm);
        Main.revalidate();
        Main.repaint();
    }//GEN-LAST:event_jButton24ActionPerformed

    String sitem = "";
    private void comprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprActionPerformed
       try{
        
            
             String sql ="select * from item where nm=?";

             pstmt = con.prepareStatement(sql);
            
             pstmt.setString(1, (String)compr.getSelectedItem());
            
             sitem = (String)compr.getSelectedItem();
             
             ResultSet set = pstmt.executeQuery();

            while(set.next())
            {
              pr.setText(set.getString(3));
              quan1.setText("Available Quantity : "+String.valueOf(set.getInt(4)));
//              double q = set.getInt(4);
//              double remainingstock = q - Double.parseDouble(quan.getText());
//              quan1.setText("Available Quantity : "+remainingstock);
            }
            
         
            
          }catch(Exception ex){
              ex.printStackTrace();
          }
    
        
    }//GEN-LAST:event_comprActionPerformed

    int tb_c = 0;
    double totalbill = 0;
    double remainingstock = 0;
    private void jButton40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton40ActionPerformed
        try {
              String q2 = "select count(id) from item";
              
               pstmt = con.prepareStatement(q2);
             
              set = pstmt.executeQuery();
              
              int rowcount = 0;
              while(set.next())
              {
                rowcount = Integer.parseInt(set.getString(1));
                
                tb.setRowCount(rowcount);
              }
              
              if(tb_c == 0)
              {
                for(int ii =0; ii<1; ii++)
                {       
                  tb.setValueAt(compr.getSelectedItem(), ii, 0);
                  tb.setValueAt(pr.getText(), ii, 1);
                  tb.setValueAt(quan.getText(), ii, 2);
                 }  

                double pri = Double.parseDouble(pr.getText());

                double qt = Double.parseDouble(quan.getText());
                
                totalbill = totalbill + (pri * qt);
                total.setText(" "+totalbill);

                
              
                  
                tb_c++;
              }
              
              else if(tb_c > 0)
              {
                for(int ii =tb_c; ii<(tb_c+1); ii++)
                {       
                  tb.setValueAt(compr.getSelectedItem(), ii, 0);
                  tb.setValueAt(pr.getText(), ii, 1);
                  tb.setValueAt(quan.getText(), ii, 2);
                 }  

                double pri = Double.parseDouble(pr.getText());

                double qt = Double.parseDouble(quan.getText());
                totalbill = totalbill + (pri * qt);
                total.setText(" "+totalbill);

              
              
              
                 tb_c++;
              }
              
              
//                String sql ="select * from item where nm=?";
//
//                pstmt = con.prepareStatement(sql);
//
//                pstmt.setString(1, (String)compr.getSelectedItem());
//
//                set = pstmt.executeQuery(sql);
//
//               while(set.next())
//               {
//                 double q = set.getInt(4);       
//                 remainingstock = q - Double.parseDouble(quan.getText());
//                 quan1.setText("Available Quantity : "+remainingstock);
//                 
//               }
            
               //......... UPDATING QUANTITY IN DATABASE.....................
//                String sql2 ="update item set qt=? where nm="+sitem;
//
//                pstmt = con.prepareStatement(sql2);
//
//                pstmt.setDouble(4, remainingstock);
//               
//                pstmt.executeUpdate();
//              double total_bill = Double.parseDouble(total.getText());
//              double paid_bill = Double.parseDouble(paid.getText());
              
              
              
          }catch (Exception ex) {
              ex.printStackTrace();
          }
          
    }//GEN-LAST:event_jButton40ActionPerformed

    private void jButton42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton42ActionPerformed
        Main.removeAll();
        Main.add(mm);
        Main.revalidate();
        Main.repaint();
    }//GEN-LAST:event_jButton42ActionPerformed

    private void jButton45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton45ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton45ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        Main.removeAll();
        Main.add(salerec);
        Main.revalidate();
        Main.repaint();
        
        try {
            
            
            //...setting values to table....................
            
            String q2 = "select count(id) from customer";
              
               pstmt = con.prepareStatement(q2);
             
              set = pstmt.executeQuery();
              
              while(set.next())
              {
                int rowcount = Integer.parseInt(set.getString(1));
                
                ts.setRowCount(rowcount);
              }
              
              
              String q = "select * from customer";
              st = con.createStatement();
              set = st.executeQuery(q);
              
              int ii = 0;
              while(set.next())
              {
                ts.setValueAt(set.getInt(1), ii, 0);
                ts.setValueAt(set.getString(2), ii, 1);
                ts.setValueAt(set.getDouble(3), ii, 2);
                ts.setValueAt(set.getString(4), ii, 3);

                ii++;
              }
              
       
            
            
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton41ActionPerformed
        try {
            String name = cusnm.getText().toString();
            double to= Double.parseDouble(total.getText().toString());
           
             String sql ="insert into customer(nm,total,dat) values(?,?,?)";

             pstmt=con.prepareStatement(sql);
            
            pstmt.setString(1, name);
            pstmt.setDouble(2, to);
            pstmt.setString(3, date());
            
            pstmt.executeUpdate();
            
            
            //...setting values to table....................
            
            String q2 = "select count(id) from customer";
              
               pstmt = con.prepareStatement(q2);
             
              set = pstmt.executeQuery();
              
              while(set.next())
              {
                int rowcount = Integer.parseInt(set.getString(1));
                
                ts.setRowCount(rowcount);
              }
              
              
              String q = "select * from customer";
              st = con.createStatement();
              set = st.executeQuery(q);
              
              int ii = 0;
              while(set.next())
              {
                ts.setValueAt(set.getInt(1), ii, 0);
                ts.setValueAt(set.getString(2), ii, 1);
                ts.setValueAt(set.getDouble(3), ii, 2);
                ts.setValueAt(set.getString(4), ii, 3);

                ii++;
              }
              
       
            
            
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton41ActionPerformed

    private void jButton47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton47ActionPerformed
       int id = Integer.parseInt(txd.getText());
       
       try {
             
              if(tsr.getSelectedRowCount() >= 1)
              {
                String q = "delete from customer where id=?";
             
               pstmt=con.prepareStatement(q);
            
              
                pstmt.setInt(1 , id);
            
                pstmt.executeUpdate();
              
                ts.removeRow(tsr.getSelectedRow());
               
              }
              
              else if(tsr.getSelectedRowCount() == 0)
              {
                JOptionPane.showMessageDialog(rootPane, "Table is Empty");
              }
              
              else{
                JOptionPane.showMessageDialog(rootPane, "Please Select a singal row");
              }
         
              
          }catch (Exception ex) {
              ex.printStackTrace();
          }
          
    }//GEN-LAST:event_jButton47ActionPerformed

    private void tsrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tsrMouseClicked
       int index = tsr.getSelectedRow();
       
       int id =  (int) ts.getValueAt(index , 0);
       
       txd.setText(""+id);
    }//GEN-LAST:event_tsrMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Main;
    private javax.swing.JPanel addp;
    private javax.swing.JTextField bal;
    private javax.swing.JPanel billingScreen;
    private javax.swing.JComboBox compr;
    private javax.swing.JTextField cusnm;
    private javax.swing.JLabel date;
    private javax.swing.JPanel deletep;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton45;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton47;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPanel mm;
    private javax.swing.JTextField paid;
    private javax.swing.JTextField pnm;
    private javax.swing.JTextField ppr;
    private javax.swing.JTextField pqt;
    private javax.swing.JTextField pr;
    private javax.swing.JPanel prmm;
    private javax.swing.JTextField quan;
    private javax.swing.JLabel quan1;
    private javax.swing.JPanel salerec;
    private javax.swing.JTable tbil;
    private javax.swing.JTable tdel;
    private javax.swing.JTextField total;
    private javax.swing.JTable tp;
    private javax.swing.JTable tsr;
    private javax.swing.JTextField txd;
    private javax.swing.JTextField txdel;
    private javax.swing.JPanel updatep;
    private javax.swing.JPanel viewp;
    // End of variables declaration//GEN-END:variables
}
